### ISSUE TITLE
What Voice Synthesizing Service Does The Website Use?

### ISSUE THREAD

**Issue by MethanJess** [theRealestAEP/EyeSpeak#1]
Hi, I tested the demo website of this repository, and I was very impressed with how realistic and emotive the voice is,

Could you please tell me what Ai Voice Generator service/software is used on the website?
Is it ElevenLabs?

**Comment by theRealestAEP** [comment]
Hey there yes its an 11labs voice - you can just replace the ENV key with your own for 11labs and the speaker id in the getSpeech route if you would like to deploy this yourself!
